### ISSUE TITLE
Can't seem to run script

### ISSUE THREAD

**Issue by StGeorgeA** [stevemeier/spacewalk-debian-sync#4]
When I attempt to run the script

./spacewalk-debian-sync.pl --username testadmin --password 'P@$$Word12345!' --channel 'ubuntu-12.04' --url 'http://de.archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/'

I get the following error:

Can't locate WWW/Mechanize.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./spacewalk-debian-sync.pl line 38.
BEGIN failed--compilation aborted at ./spacewalk-debian-sync.pl line 38.

**Comment by stevemeier** [comment]
The script requires the WWW::Mecahnize module.

It is available in CentOS and Debian through the normal package
management infrastructure (yum, apt-get).

Kind regards,
   Steve

Am 2014-11-10 17:21, schrieb StGeorgeA:

**Comment by StGeorgeA** [comment]
perl-WWW-Mechanize.noarch or python-mechanize.noarch?

**Comment by StGeorgeA** [comment]
I installed perl-WWW-Mechanize and got a little closer.

My current error is now...

 ./spacewalk-debian-sync.pl --username testadmin --password 'P@$$Word12345!' --channel 'ubuntu-12.04' --url 'http://de.archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/'
INFO: Repo URL: http://de.archive.ubuntu.com/ubuntu/dists/precise/main/binary-amd64/
INFO: Ubuntu root is http://de.archive.ubuntu.com/ubuntu/
INFO: Fetching Packages.gz... done
INFO: Packages in repo:         8076
INFO: Packages already synced:  0
INFO: Packages to sync:         8076
INFO: 1/8076 : language-pack-si_12.04+20120417_all.deb

ERROR: unhandled exception occurred: (Certificate file /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT is not accessible).
ERROR: rhnpush failed

**Comment by StGeorgeA** [comment]
cp -p /var/www/html/pub/RHN-ORG-TRUSTED-SSL-CERT /usr/share/rhn/RHN-ORG-TRUSTED-SSL-CERT

**Comment by StGeorgeA** [comment]
Error Class Code: 2
Error Class Info: Invalid username and password combination.

What username & password combination is the script needing?

**Comment by StGeorgeA** [comment]
If your password contains special characters like $, & and a few others this will fail.

Special characters were removed from the password and the script is working correcty
