### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by MarcusCaepio** [stevemeier/spacewalk-debian-sync#6]
Hi Steve,
when I try to execute you script as written in
http://www.devops-blog.net/spacewalk/registering-ubuntu-and-debian-servers-with-spacewalk
I get a syntax error:
./spacewalk-debian-sync.pl: Zeile 1: Syntaxfehler beim unerwarteten Wort `newline'
./spacewalk-debian-sync.pl: Zeile 1:`<!DOCTYPE html>'

**Comment by stevemeier** [comment]
This seems to be a download error, not really related to the script. Make sure you use the "raw" link, when downloading from GitHub directly. Try this link:

https://raw.githubusercontent.com/stevemeier/spacewalk-debian-sync/master/spacewalk-debian-sync.pl

Kind regards,
  Steve
