### ISSUE TITLE
File not a package

### ISSUE THREAD

**Issue by MarcusCaepio** [stevemeier/spacewalk-debian-sync#7]
So I got your last script version and installed all necessary modules. But the sync stops:

./spacewalk-debian-sync.pl --username admin --password *****\* --channel trusty-updates --url 'http://de.archive.ubuntu.com/ubuntu/dists/trusty/main/binary-amd64/'

INFO: 1/8557 : language-pack-gnome-mt-base_14.04+20140410_all.deb
ERROR: /tmp/language-pack-gnome-mt-base_14.04+20140410_all.deb: This file doesn't appear to be a package
ERROR: rhnpush failed

**Comment by stevemeier** [comment]
Hello,

this error message is from the rhnpush utility, which is part of Spacewalk. My script downloads the packages and then calls rhnpush to load them into Spacewalk. Please open a bug with Spacewalk or check their Mailing List (Archives) for this issue.

Kind regards,
  Steve

**Comment by baskarc12** [comment]
Hello Steve..,
i'm also facing the same issue...
INFO: 1/8557 : language-pack-gnome-mt-base_14.04+20140410_all.deb
ERROR: /tmp/language-pack-gnome-mt-base_14.04+20140410_all.deb: This file doesn't appear to be a package
ERROR: rhnpush failed

Thanks & regards,
Baskar

**Comment by mkrsn** [comment]
Try https://bugzilla.redhat.com/attachment.cgi?id=1086524 - it should fix your Problem.

**Comment by saravananarumugam2207** [comment]
How to apply this ? 
https://bugzilla.redhat.com/attachment.cgi?id=1086524
